source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

def pods
    pod 'AFNetworking'
    pod 'Socket.IO-Client-Swift'
    pod 'Reachability'
    pod 'YYModel'
    pod 'Masonry'
    pod 'AgoraRtcEngine_iOS'
    pod 'Cordova', '4.3.0'

    #pod 'MLeaksFinder', :configurations => ['Debug']
    pod 'Reveal-iOS-SDK', :configurations => ['Debug']

end

target 'Classroom3' do
    pods
end
